---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: instrumentation-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 776944552541.dkr.ecr.ap-southeast-2.amazonaws.com/order-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: instrumentation-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: 776944552541.dkr.ecr.ap-southeast-2.amazonaws.com/inventory-service:latest
        ports:
        - containerPort: 9082
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-service
  namespace: instrumentation-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coupon-service
  template:
    metadata:
      labels:
        app: coupon-service
    spec:
      containers:
      - name: coupon-service
        image: 776944552541.dkr.ecr.ap-southeast-2.amazonaws.com/coupon-service:latest
        ports:
        - containerPort: 9081
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfilment-service
  namespace: instrumentation-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fulfilment-service
  template:
    metadata:
      labels:
        app: fulfilment-service
    spec:
      containers:
      - name: fulfilment-service
        image: 776944552541.dkr.ecr.ap-southeast-2.amazonaws.com/fulfilment-service:latest
        ports:
        - containerPort: 9083
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-server
  namespace: instrumentation-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spa-server
  template:
    metadata:
      labels:
        app: spa-server
    spec:
      containers:
      - name: spa-server
        image: 776944552541.dkr.ecr.ap-southeast-2.amazonaws.com/spa-server:latest
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"