---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: instrumentation-workshop
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: instrumentation-workshop
spec:
  selector:
    app: inventory-service
  ports:
    - port: 9082
      targetPort: 9082
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: instrumentation-workshop
spec:
  selector:
    app: coupon-service
  ports:
    - port: 9081
      targetPort: 9081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fulfilment-service
  namespace: instrumentation-workshop
spec:
  selector:
    app: fulfilment-service
  ports:
    - port: 9083
      targetPort: 9083
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: spa-server
  namespace: instrumentation-workshop
spec:
  selector:
    app: spa-server
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: instrumentation-workshop
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: instrumentation-workshop
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: instrumentation-workshop
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP